### ISSUE TITLE
Load extensions to menu

### ISSUE THREAD

**Issue by Sential** [Nersent/Wexond#4]

**Comment by Pietrafixa** [comment]
It would be perfect if it were possible to add support for Google Chrome extensions.

**Comment by Sential** [comment]
@Pietrafixa Sorry, but unfortunately there is no way to integrate Chrome extensions with Electron. I'm creating my own API for extensions.

**Comment by Pietrafixa** [comment]
I understand @Sential. It would have been very productive. My advice is to also craere an extension that allows you to block advertisements (AdBlock). Now all latest browsers offer this technology. Anyway great job. You're bright.

**Comment by Sential** [comment]
@Pietrafixa Thank you. In my browser will be something like AdBlock (I'm using this too). I'm planning to make a lot of functions in extensions API.

**Comment by Pietrafixa** [comment]
Great! @Sential. Another advice I can give you is to implement notifications. Now the latest sites (Facebook, WhatsApp Web, twetter, etc.) use this function.

**Comment by Pietrafixa** [comment]
Hello @Sential, I am writing here because this was closed Issues.
I wanted to ask you a favor? Could you give me a hand on this file:
It is a written Server Node.js. (I am not very experienced in this field.) Not knowing where to turn, I immediately thought of you. Who better than you, who work in this field every day. However my problem is that I want to create an executable (.exe) for this server, so that you to run the server as a common PC software. Could you help me? Thank you so much!

PS
This server uses MongoDB (3.4.x) as datebase.

**Comment by Sential** [comment]
Hello, if you want to compile your node js application you should use [nexe](https://github.com/nexe/nexe). I haven't compiled node js application to exe yet, but I think nexe is great option for you.

**Comment by Pietrafixa** [comment]
I try Nexe. Thank you very much.
